### ISSUE TITLE
Scope parameter in token response example

### ISSUE THREAD

**Issue by pcornish** [govuk-one-login/authentication-tech-docs#121]
In [Receive response for ‘Make a token request’
](https://docs.sign-in.service.gov.uk/integrate-with-integration-environment/integrate-with-code-flow/#receive-response-for-make-a-token-request) an example response is provided:

```json
{
  "access_token": "SlAV32hkKG",
  "refresh_token": "i6mapTIAVSp2oJkgUnCACKKfZxt_H5MBLiqcybBBd04",
  "token_type": "Bearer",
  "expires_in": 180,
  "id_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjFlOWdkazcifQ.ewogImlzcyI6ICJodHRwOi8vc2VydmVyLmV4YW1wbGUuY29tIiwKICJzdWIiOiAiMjQ4Mjg"
}
```

This example doesn't include the `scope` parameter and the subsequent table doesn't indicate which parameters are expected ('required'). The table does, however, refer the reader back to the scopes documentation page.

If the `scope` is always returned from the `/token` endpoint we should update the example to include it. If it is not always returned, then we should update the table to indicate it is an optional parameter and describe the conditions under which the relying party should expect to receive it.

**Comment by pauldougan** [comment]
Moved into the tech docs backlog in Jira [AP-180](https://govukverify.atlassian.net/browse/AP-180)
