### ISSUE TITLE
Create a default issue template to structure information gathered

### ISSUE THREAD

**Issue by pauldougan** [govuk-one-login/authentication-tech-docs#175]
At the moment new issues have no structure and are free format. 

We should add a simple template to help structure the issues so that we are able to understand user needs.

There must be some good examples elsewhere in use at GDS we can look at for inspiration

**Comment by pauldougan** [comment]
the design system has a number of templates for their issues https://github.com/alphagov/govuk-design-system/issues/new/choose

**Comment by huwd** [comment]
Likely a good idea to cross reference it with our PR template too?
What checks do we want people to have done by PR stage that they could begin exploring at issue?
https://github.com/govuk-one-login/authentication-tech-docs/blob/main/.github/pull_request_template.md

**Comment by pauldougan** [comment]
we need to bear in mind the the users of this issue template are not GDS insiders but people in other government departments and their delivery partners who are using the technical documentation to build integrations.

**Comment by pauldougan** [comment]
@jankishah-gds any chance you can add the issue template you are working on from the DI team manual? https://github.com/govuk-one-login/team-manual/pull/505 we need this for the One Login Tech docs.

**Comment by pauldougan** [comment]
closing this issue and moving it to JIRA [AP-181](https://govukverify.atlassian.net/browse/AP-181)
