### ISSUE TITLE
Table formatting

### ISSUE THREAD

**Issue by galund** [govuk-one-login/authentication-tech-docs#78]
Our tables have lots of this:

```
<span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">...</span>
```

We should replace this with a class on the table element (or td, or whatever), or just some CSS rules, or whatever :-)

**Comment by elenaschwan** [comment]
Addressed in [PR-144](https://github.com/govuk-one-login/authentication-tech-docs/pull/144)

**Comment by pauldougan** [comment]
Hi @galund the tech docs tables have received some love via the PR above so I am closing this issue
